### ISSUE TITLE
use_operation_from_file does not work on AFM files

### ISSUE THREAD

**Issue by pabpazjim** [diverso-lab/fm_metamodel#56]
When running use_operation_from_file from DiscoverMetamodels and giving an afm file as input:

![image](https://user-images.githubusercontent.com/43904563/146523840-a01e7974-42ee-4896-9bd8-4c84fd6b582b.png)

I am getting this output:

![image](https://user-images.githubusercontent.com/43904563/146523658-2751502a-0a15-4d4b-b7b0-ea4fbcc8e3de.png)

**Comment by Virako** [comment]
@jagalindo yes
